version: '2.2'

services:
  redis-replica:
    image: 'redis:6'
    container_name: redis_slave
    command: redis-server /etc/redis-config/redis.conf
    ports:
      - '6379:6379'
    # depends_on:
    #    - redis-master
    volumes:
      - ./redis_data/redis_replication:/data
      - ./config/redis-slave:/etc/redis-config
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=192.168.0.157
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=1234
      - REDIS_PASSWORD=123
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHAL 

    networks:
      - redis-network
volumes:
  redis_data:
    name: redis-vl
    driver: local
    # external: true
networks:
 redis-network:
    driver: bridge